services:
  - type: web
    name: experiment-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
